language: java
jdk:
- oraclejdk12
before_install:
- openssl aes-256-cbc -K $encrypted_b836b1ff717a_key -iv $encrypted_b836b1ff717a_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
jobs:
  include:
  - stage: build
    install:
    - true
    script:
    - "./gradlew build --stacktrace --scan"
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build --file auxilyo-test-doubles-wiremock/Dockerfile --build-arg INFO_APP_BUILD=$TRAVIS_BUILD_NUMBER
      --tag auxilyo/auxilyo-wiremock:$TRAVIS_BUILD_NUMBER .
    - docker push auxilyo/auxilyo-wiremock:$TRAVIS_BUILD_NUMBER
    - docker build --file auxilyo-test-doubles-greenmail/Dockerfile --build-arg JAR_FILE=auxilyo-test-doubles-greenmail/build/libs/my-security-officer-greenmail.jar
      --build-arg INFO_APP_BUILD=$TRAVIS_BUILD_NUMBER --tag auxilyo/auxilyo-greenmail:$TRAVIS_BUILD_NUMBER
      .
    - docker push auxilyo/auxilyo-greenmail:$TRAVIS_BUILD_NUMBER
  - stage: DEV deploy
    install:
    - true
    script:
    - |
      ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@auxilyo-test-doubles.lucid.works /bin/bash -s << EOT
      docker ps -a -q | xargs docker stop;
      docker images -a -q | xargs docker rmi;
      docker system prune -a -f;
      docker run -d --rm -p 9090:8080 auxilyo/auxilyo-wiremock:$TRAVIS_BUILD_NUMBER
      docker run -d --rm -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995 auxilyo/auxilyo-greenmail:$TRAVIS_BUILD_NUMBER
      EOT
