language: java
jdk:
- oraclejdk12
before_install:
- openssl aes-256-cbc -K $encrypted_b836b1ff717a_key -iv $encrypted_b836b1ff717a_iv
  -in lucid_works.enc -out lucid_works -d
- chmod 600 lucid_works
- mv lucid_works ~/.ssh/id_rsa
jobs:
  include:
  - stage: Build
    install:
    - true
    script:
    - "./gradlew build --stacktrace --scan"
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build --file metrofox-test-doubles-wiremock/Dockerfile
      --build-arg INFO_APP_BUILD=$TRAVIS_BUILD_NUMBER
      --tag metrofoxservices/metrofox-test-doubles-wiremock:$TRAVIS_BUILD_NUMBER .
    - docker push metrofoxservices/metrofox-test-doubles-wiremock:$TRAVIS_BUILD_NUMBER
    - docker build --file metrofox-test-doubles-greenmail/Dockerfile
      --build-arg JAR_FILE=metrofox-test-doubles-greenmail/build/libs/metrofox-test-doubles-greenmail.jar
      --build-arg INFO_APP_BUILD=$TRAVIS_BUILD_NUMBER
      --tag metrofoxservices/metrofox-test-doubles-greenmail:$TRAVIS_BUILD_NUMBER .
    - docker push metrofoxservices/metrofox-test-doubles-greenmail:$TRAVIS_BUILD_NUMBER
  - stage: DEV deploy
    install:
    - true
    script:
    - |
      ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@metrofox-test-doubles.lucid.works /bin/bash -s << EOT
      docker ps -a -q | xargs -r docker stop;
      docker images -a -q | xargs -r docker rmi;
      docker system prune -a -f;
      docker run -d --rm -p 9090:8080 metrofoxservices/metrofox-test-doubles-wiremock:$TRAVIS_BUILD_NUMBER
      docker run -d --rm -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995 metrofoxservices/metrofox-test-doubles-greenmail:$TRAVIS_BUILD_NUMBER
      EOT
